io:
  n: 1

cot:
  n: 1

cot_sc:
  n: 10
  
foa:
  num_agents: 4
  num_steps: 4
  k: 2
  backtrack: 0.5
  resampling: "linear"
  min_steps: 1
  num_evaluations: 3
  origin: 150

tot_bfs:
  num_selections: 5
  num_steps: 3
  num_evaluations: 3

tot_dfs:
  num_selections: 3
  num_steps: 6
  num_evaluations: 3
  pruning_threshold: 0
  max_iterations: 10
  
got:
  num_selections: 2
  num_steps: 1
  num_generate: 5
  num_evaluations: 1
  num_best: 2

react:
  num_steps: 10

rap:
  num_iterations: 10
  num_samples: 5
  num_evaluations: 3
  exploration_constant: 1.0
  max_depth: 10